### PR TITLE
Update HeritagePIDs homepage, add about and resources page. 

### PR DESCRIPTION
**Pull request by FrancesMadden**
For about page

### CODE REVIEW

**Comment by jpadfield** [comment]
Hi, Just in case it is useful I did do an simple extension to add a gallery of logos, see: https://tanc-ahrc.github.io/IIIF-TNC/about.html 

Might this be useful?

**Comment by FrancesMadden** [comment]
I'm in the process of creating a new page based on it! :)

**Comment by jpadfield** [comment]
Ok :-)

**Comment by jpadfield** [comment]
I am not sure anyone else has tested that one, so any comments or suggestions do let me know.

**Pull request closed without merging**
